[package]
name = "aoc-2025"
version = "0.1.9"
edition = "2024"
publish = false

[dependencies]
png_encode_mini = "0.1.2"
good_lp = { version = "1", default-features = false, features = ["lp-solvers"] }

[profile.release]
debug = true

